apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://political-referrals-wa-331919709696.us-central1.run.app","https://political-referrals-wa-pucx27zqna-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: political-referrals-wa
  namespace: '331919709696'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 534.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: gewplgpntf
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        image: gcr.io/intreasoft-daniel/political-referrals-wa:b878c1ef70a818f9f956e38923c379c12dbe2b05
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 331919709696-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
