apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: political-referrals-wa
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/political-referrals-wa:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: SPRING_CLOUD_GCP_PROJECT_ID
              key: latest
        - name: WEBHOOK_VERIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: webhook-verify-token
              key: latest
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-token
              key: latest
        - name: TELEGRAM_BOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: TELEGRAM_BOT_USERNAME
              key: latest
        - name: WATI_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: WATI_TENANT_ID
              key: latest
        - name: WATI_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wati-api-token
              key: latest
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest
        - name: ANALYTICS_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: analytics-jwt-secret
              key: latest
        - name: WATI_NOTIFICATION_ENABLED
          valueFrom:
            secretKeyRef:
              name: WATI_NOTIFICATION_ENABLED
              key: latest
        - name: WATI_NOTIFICATION_GROUP_ID
          valueFrom:
            secretKeyRef:
              name: WATI_NOTIFICATION_GROUP_ID
              key: latest
        - name: WATI_NOTIFICATION_PHONES
          valueFrom:
            secretKeyRef:
              name: WATI_NOTIFICATION_PHONES
              key: latest
        - name: WATI_API_ENDPOINT_BASE
          valueFrom:
            secretKeyRef:
              name: wati-api-endpoint-base
              key: latest
        - name: AI_BOT_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: ai-bot-endpoint
              key: latest
        - name: GEMINI_API_URL
          valueFrom:
            secretKeyRef:
              name: gemini-api-url
              key: latest
        - name: CHATBOT_IA_URL
          valueFrom:
            secretKeyRef:
              name: chatbot-ia-url
              key: latest
        - name: ANALYTICS_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: analytics-endpoint-url
              key: latest
        - name: WELCOME_VIDEO_URL
          valueFrom:
            secretKeyRef:
              name: welcome-video-url
              key: latest
