apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: political-referrals-wa
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: false
        run.googleapis.com/startup-cpu-boost: true
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/political-referrals-wa:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_GCP_PROJECT_ID
          value: "YOUR_PROJECT_ID"
        - name: WEBHOOK_VERIFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: webhook-verify-token
              key: latest
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-token
              key: latest
        - name: TELEGRAM_BOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: telegram-bot-username
              key: latest
        - name: WATI_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: wati-tenant-id
              key: latest
        - name: WATI_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: wati-api-token
              key: latest
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest
        - name: ANALYTICS_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: analytics-jwt-secret
              key: latest
        - name: WATI_NOTIFICATION_ENABLED
          value: "true"
        - name: WATI_NOTIFICATION_GROUP_ID
          valueFrom:
            secretKeyRef:
              name: wati-notification-group-id
              key: latest
        - name: WATI_NOTIFICATION_PHONES
          valueFrom:
            secretKeyRef:
              name: wati-notification-phones
              key: latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
