apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: political-referrals-wa
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/political-referrals-wa:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CLOUD_GCP_PROJECT_ID
          value: "intreasoft-daniel"
        - name: WEBHOOK_VERIFY_TOKEN
          value: "qaRZjTs8tFTfo5pLt6JwyFtGFPtuxLF6JBYqu0YcXsQ"
        - name: TELEGRAM_BOT_TOKEN
          value: "7350149841:AAHsujWqzvh9azw2dMlwby6iZdlEkmisSv4"
        - name: TELEGRAM_BOT_USERNAME
          value: "ResetPoliticaBot"
        - name: WATI_TENANT_ID
          value: "473173"
        - name: WATI_API_TOKEN
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5ZWViNzJlZi01NmVmLTQzZjUtYjBmOC00NWFjZTVjZjBiZjgiLCJ1bmlxdWVfbmFtZSI6ImludHJhc29mdGRldm9wc0BnbWFpbC5jb20iLCJuYW1laWQiOiJpbnRyYXNvZnRkZXZvcHNAZ21haWwuY29tIiwiZW1haWwiOiJpbnRyYXNvZnRkZXZvcHNAZ21haWwuY29tIiwiYXV0aF90aW1lIjoiMDcvMjUvMjAyNSAyMzo0MzowOSIsInRlbmFudF9pZCI6IjQ3MzE3MyIsImRiX25hbWUiOiJtdC1wcm9kLVRlbmFudHMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBRE1JTklTVFJBVE9SIiwiZXhwIjoyNTM0MDIzMDA4MDAsImlzcyI6IkNsYXJlX0FJIiwiYXVkIjoiQ2xhcmVfQUkifQ._mgHJCUNWWmdVueTQmoEAEtaIZS9uTkOwh28UffXFDg"
        - name: GEMINI_API_KEY
          value: "AIzaSyA73v4PVS8kaID6TWQcW-F31qPk2BiBNHo"
        - name: ANALYTICS_JWT_SECRET
          value: "z4PiqjH5bJEUTcDLz4q//FX4MZXvrN7vQi+38KK5r1g="
        - name: WATI_NOTIFICATION_ENABLED
          value: "true"
        - name: WATI_NOTIFICATION_GROUP_ID
          value: ""
        - name: WATI_NOTIFICATION_PHONES
          value: "573227281752"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 8
      scaling:
        minScale: 0
        maxScale: 10
        targetCPUUtilization: 70
        targetMemoryUtilization: 80 